# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 09:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=datetime.datetime(2016, 2, 16, 9, 20, 36, 866784, tzinfo=utc), upload_to='myblog/image/svg-icons'),
            preserve_default=False,
        ),
    ]
