# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20160216_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(default=datetime.datetime(2016, 2, 16, 12, 49, 22, 642033, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
