# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20160216_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='background_color',
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
    ]
