# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 06:40
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20160229_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tage',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
