# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20170205_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_date',)},
        ),
    ]
