# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_post_tage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tage',
            new_name='tag',
        ),
    ]
