# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 07:17
from __future__ import unicode_literals

from django.db import migrations
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20170225_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=simplemde.fields.SimpleMDEField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=simplemde.fields.SimpleMDEField(verbose_name='body'),
        ),
    ]
