# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 04:24
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20161109_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
