# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20170225_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=simplemde.fields.SimpleMDEField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=simplemde.fields.SimpleMDEField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
