# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 04:58
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20170225_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_markdown.models.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
