# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='published_date',
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
