# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0014_auto_20170908_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='author',
        ),
        migrations.RemoveField(
            model_name='about',
            name='created_date',
        ),
    ]
