# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0017_auto_20170908_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='body',
        ),
    ]
