# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 00:20
from __future__ import unicode_literals

from django.db import migrations
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0018_auto_20170908_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=simplemde.fields.SimpleMDEField(verbose_name='mardown content'),
        ),
    ]
