# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 01:53
from __future__ import unicode_literals

from django.db import migrations
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0019_auto_20170915_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=simplemde.fields.SimpleMDEField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=simplemde.fields.SimpleMDEField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=simplemde.fields.SimpleMDEField(verbose_name=''),
        ),
    ]
